development:
  adapter: postgresql
  encoding: unicode
  database: marketem_development

test: &test
  adapter: postgresql
  encoding: unicode
  database: marketem_test

production:
  adapter: postgresql
  encoding: unicode
  database: marketem_production

cucumber:
  <<: *test